# Generated by Django 4.2.5 on 2023-09-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_tag_note_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
